version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: article_db
            POSTGRES_USER: knowledge_base
            POSTGRES_PASSWORD: knowledge_base
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
